### ISSUE TITLE
🚸  Auto send private message

### ISSUE THREAD

**Issue by ascpial** [TI-Planet/ShoutBot#57]
Send private message to the user who as sended the message does not show the advanced message.

**Comment by Wistaro** [comment]
> Send private message to the user who as sended the message does not show the advanced message.

What do you mean by "does not show the advanced message" ?

**Comment by adriweb** [comment]
Probably "doesn't show the previous message" (message d'avant)

**Comment by Hayleia** [comment]
This kind of message, on selfbots.
![image](https://user-images.githubusercontent.com/7904776/111627978-f870af00-87ef-11eb-8853-a1b569436b6e.png)
And when replying to it, the message is sent as private message too.

When talking to yourself, this is the result.
![image](https://user-images.githubusercontent.com/7904776/111628176-366dd300-87f0-11eb-8722-9ecf3e2e9f1c.png)
So no "advanced message" as in the previous screenshot.

However from my understanding, sending a /msg on tiplanet generates a /privmsg for the receiver and a /privmsgto for the sender, both to be parsed by the chat and be displayed as "murmure"/"whisper" on the respective clients.
Among these two messages, I guess that the /privmsg one is treated as "the message on tiplanet that is equivalent to the one that was sent on discord" and that's why it doesn't come back on discord, while the /privmsgto appears.
Notice that if you send a /msg on tiplanet directly, you get both because none of them is considered to be already present on discord.
![image](https://user-images.githubusercontent.com/7904776/111629671-d4ae6880-87f1-11eb-9bed-ec5301142596.png)

Currently the bridge only parses /privmsg, so received messages, not generated sent messages that came back because you're the one who sent them. So it's not an edge case bug, it's more like the feature not extending to an edge case. We can discuss what we want to do in that edge case (several options possible):
- ignore /privmsgto?
- make a special case of /msg so that the /privmsg comes back?
- parse /privmsgto as if it was a /privmsg even though it's not?
- do nothing?

Taking into acount that:
- it's an edge case, who talks to themselves?
- who talks to themselves... on tiplanet's chat from discord? I mean I know people who talk to themselves to keep important links and stuff but while you're on discord, just send a private message to a random bot account or something instead of putting your bookmarks in the middle of the bridge?

My vote is "do nothing" because it allows checking that the bridge works if we don't ignore them, parsing /privmsgto would be pointless if that's the only usecase and I don't see any other relevant usecase, ignoring /privmsgto AND making a special case to allow the /privmsg to come back would be the cleanest way but once again it's an edge case so probably not worth the effort.

**Comment by Hayleia** [comment]
Some clarifications.
When I say "selfbots" I mean tiplanet-side selfbots, not discord-side selfbots which are against the TOS.
When I say "not worth the effort", I don't mean "too hard, no time", I mean "why add complexity to the codebase to be maintained forever only for a usecase the majority of users don't care about and minorities of users will disagree with what they want about it?".
